# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 04:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20161116_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usrname', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='nombrealbum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomalb', to='posts.Archivos'),
        ),
    ]
