# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 06:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20161117_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='usuar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usrname', to=settings.AUTH_USER_MODEL),
        ),
    ]
